language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 7ae25f85665eab08b3972009922a85f28694478fd93c0f0343337be9f8d95d0d
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
  - bash travis-after-build.sh
